/**
 * \file        event_record.h
 * \date        2024-07-05
 * \author      (NR) Nenad Radulovic (nenad.b.radulovic@gmail.com)
 *
 * \brief       Event record structure interface
 *
 * \li          2024-07-05  (NR) Initial implementation
 *
 * \copyright   Dometic Group
 *              This source file and the information contained in it are
 *              confidential and proprietary to Dometic Group
 *              The reproduction or disclosure, in whole or in part,
 *              to anyone outside of Dometic Group without the written
 *              approval of a Dometic Group officer under a Non-Disclosure
 *              Agreement is expressly prohibited.
 *
 *              All rights reserved
 */

#ifndef EVENT_RECORD_H_
#define EVENT_RECORD_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "connector_event_notification_defaults.h"
#include "ddm_entry.h"

/**
 * @brief       Event record is acknowledged for application.
 */
#define EVENT_RECORD_FLAG_APP_ACKNOWLEDGED (0x1 << 0)

/**
 * @brief       Event record is sent to cloud.
 *
 * When this flag is set it indicates that the event record has been sent to the MQTT connector.
 *
 * In future, MQTT might also tell to EVM that the event record has been received by the cloud.
 * In that case EVENT_RECORD_FLAG_CLOUD_ACKNOWLEDGED flag will be set.
 */
#define EVENT_RECORD_FLAG_CLOUD_SENT (0x1 << 1)

/**
 * @brief       Event record is acknowledged for cloud.
 *
 * This flag is reserved for future use. It will be used when MQTT connector will
 * inform EVM that the event record has been received by the cloud.
 */
#define EVENT_RECORD_FLAG_CLOUD_ACKNOWLEDGED (0x1 << 2)

/**
 * @brief       Event record operation success code
 */
#define EVENT_RECORD_OP_SUCCESS 0

/**
 * @brief       Event record operation failure code
 */
#define EVENT_RECORD_OP_FAILURE 1

/**
 * @brief       Event timestamp type
 */
typedef uint32_t event_timestamp_t;

/**
 * @brief       Event identification type
 */
typedef int32_t event_id_t;

/**
 * @brief       Event record data type
 */
typedef enum event_record_data_type
{
    EVENT_RECORD_DATA_TYPE_TRIGGER = 0x1,    //!< Data is trigger data
    EVENT_RECORD_DATA_TYPE_PARAMETER = 0x2,  //!< Data is parameter data
} event_record_data_type_t;

/**
 *  @brief      Structure definition for an event record.
 *
 * Event records are stored in event_record database. They are generated by
 * request (evm0trig). Actual data which is stored in an event record is defined
 * by @ref event_type_t structures.
 *
 * One event_record can hold up to
 * @ref CONNECTOR_EVENT_NOTIFICATION_MAX_DATA_IN_EVENT_RECORD values.
 */
typedef struct event_record
{
    event_id_t id;         //!< Unique ID for this device
    event_timestamp_t ts;  //!< Timestamp in UTC
    int32_t type;          //!< Event type
    uint32_t flags;        //!< Event record flags, see EVENT_RECORD_FLAG_... definitions
    size_t data_size;      //!< Number of data elements
    struct event_record_data
    {
        event_record_data_type_t data_type;  //!< Data type (trigger or parameter)
        union
        {
            int32_t trigger;        //!< Trigger value, can be only int32_t
            ddm_entry_t parameter;  //!< DDM parameter value, see @ref ddm_entry_t
        };
    } data[CONNECTOR_EVENT_NOTIFICATION_MAX_DATA_IN_EVENT_RECORD];
} event_record_t;

/**
 * @brief       Initialize an event_record structure.
 *
 * When created it only knows @a event_id and @a type. Actual DDM parameters are
 * added after creating using @ref event_record_add_ddm function.
 *
 * @param       er is a pointer to event record instance that needs to be
 *              initialized.
 * @param       id is event identifier.
 * @param       type is event type identifier.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
void event_record_init(event_record_t *er, event_id_t id, int32_t type);

/**
 * @brief       Terminate a event_record instance.
 *
 * If this event record instance has allocated ddm_entry values it will
 * terminate them.
 *
 * @param       er is a pointer to event record instance that needs to be
 *              terminated.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
void event_record_terminate(event_record_t *er);

/**
 * @brief       Add a DDM entry to event record.
 *
 * DDM entry is copied to the event record.
 *
 * @param       er is a pointer to event record instance.
 * @param       source is a pointer to DDM entry whose value will be copied
 *              over to DDM entry which is part of the event record.
 * @param       f_offset is the offset in bytes from the start of the DDM entry
 *              value. This is used to indicate which part of the DDM entry
 *              value should be copied to the event record.
 * @param       f_size is the size in bytes of the DDM entry value. This is used
 *              to indicate how many bytes of the DDM entry value should be copied
 *              to the event record.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 * @pre         Number of added DDM parameters must not exceede the number of
 *              parameters defined by
 *              @ref CONNECTOR_EVENT_NOTIFICATION_MAX_DATA_IN_EVENT_RECORD
 * @return      Returns operation status.
 * @retval      EVENT_RECORD_OP_SUCCESS - operation was successful
 * @retval      EVENT_RECORD_OP_FAILURE - operation was not successful
 */
int event_record_add_parameter_data(event_record_t *er, const ddm_entry_t *source, size_t f_offset, size_t f_size);

/**
 * @brief       Add a trigger value to event record.
 *
 * @param       er is a pointer to event record instance.
 * @param       trigger_value is the trigger value to be added to the event record.
 * @param       f_offset is the offset in bytes from the start of the trigger
 *              value. This is used to indicate which part of the trigger value
 *              should be copied to the event record.
 * @param       f_size is the size in bytes of the trigger value. This is used
 *              to indicate how many bytes of the trigger value should be copied
 *              to the event record.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 * @pre         Number of added triggers must not exceede the number of
 *              parameters defined by
 *              @ref CONNECTOR_EVENT_NOTIFICATION_MAX_DATA_IN_EVENT_RECORD
 * @return      Returns operation status.
 * @retval      EVENT_RECORD_OP_SUCCESS - operation was successful
 * @retval      EVENT_RECORD_OP_FAILURE - operation was not successful
 */
int event_record_add_trigger_data(event_record_t *er, int32_t trigger_value, size_t f_offset, size_t f_size);

/**
 * @brief       Set event record timestamp.
 *
 * When event records are created they are immidiatelly timestamped. With this
 * function the timestamp can be overridden.
 *
 * @param       er is a pointer to event record instance.
 * @param       ts is new timestamp to be set.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
inline void event_record_set_ts(event_record_t *er, event_timestamp_t ts)
{
    er->ts = ts;
}

/**
 * @brief       Get event record timestamp.
 *
 * @param       er is a pointer to event record instance.
 * @return      Returns event timestamp.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
inline event_timestamp_t event_record_get_ts(const event_record_t *er)
{
    return er->ts;
}

/**
 * @brief       Set event record new acknowledge flag.
 *
 * @param       er is a pointer to event record instance.
 * @param       is_acknowledged is new acknowledge state to be set. When true
 *              event record is acknowledged, otherwise it is not acknowledged.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
inline void event_record_set_app_acknowledged(event_record_t *er, bool is_acknowledged)
{
    if (is_acknowledged)
    {
        er->flags |= EVENT_RECORD_FLAG_APP_ACKNOWLEDGED;
    }
    else
    {
        er->flags &= ~EVENT_RECORD_FLAG_APP_ACKNOWLEDGED;
    }
}

/**
 * @brief       Is event record acknowledged?
 *
 * @param       er is a pointer to event record instance.
 *
 * @retval      Returns acknowledge status.
 * @retval      true is returned when event record is acknowledged.
 * @retval      false is returned when event record is not acknowledged.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
inline bool event_record_is_app_acknowledged(const event_record_t *er)
{
    return er->flags & EVENT_RECORD_FLAG_APP_ACKNOWLEDGED ? true : false;
}

/**
 * @brief       Set event record cloud sent flag.
 *
 * @param       er is a pointer to event record instance.
 * @param       is_sent is new cloud sent state to be set. When true
 *              event record is marked as sent to the cloud, otherwise it is not sent.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
inline void event_record_set_cloud_sent(event_record_t *er, bool is_sent)
{
    if (is_sent)
    {
        er->flags |= EVENT_RECORD_FLAG_CLOUD_SENT;
    }
    else
    {
        er->flags &= ~EVENT_RECORD_FLAG_CLOUD_SENT;
    }
}

/**
 * @brief       Is event record sent to cloud?
 *
 * @param       er is a pointer to event record instance.
 * @retval      Returns cloud sent status.
 * @retval      true is returned when event record is sent to cloud.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
inline bool event_record_is_cloud_sent(const event_record_t *er)
{
    return er->flags & EVENT_RECORD_FLAG_CLOUD_SENT ? true : false;
}

/**
 * @brief       Set event record cloud acknowledged flag.
 *
 * @param       er is a pointer to event record instance.
 * @param       is_acknowledged is new cloud acknowledged state to be set. When true
 *              event record is marked as acknowledged by cloud, otherwise it is not acknowledged.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
inline void event_record_set_cloud_acknowledged(event_record_t *er, bool is_acknowledged)
{
    if (is_acknowledged)
    {
        er->flags |= EVENT_RECORD_FLAG_CLOUD_ACKNOWLEDGED;
    }
    else
    {
        er->flags &= ~EVENT_RECORD_FLAG_CLOUD_ACKNOWLEDGED;
    }
}

/**
 * @brief       Is event record acknowledged by cloud?
 *
 * @param       er is a pointer to event record instance.
 *
 * @retval      Returns acknowledge status.
 * @retval      true is returned when event record is acknowledged by cloud.
 * @retval      false is returned when event record is not acknowledged by cloud.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
inline bool event_record_is_cloud_acknowledged(const event_record_t *er)
{
    return er->flags & EVENT_RECORD_FLAG_CLOUD_ACKNOWLEDGED ? true : false;
}

/**
 * @brief       Set event record flags.
 *
 * @param       er is a pointer to event record instance.
 * @param       flags is new flags value to be set.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
inline void event_record_set_flags(event_record_t *er, uint32_t flags)
{
    er->flags = flags;
}

/**
 * @brief       Get event record flags.
 *
 * @param       er is a pointer to event record instance.
 * @retval      Returns event record flags.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
inline uint32_t event_record_get_flags(const event_record_t *er)
{
    return er->flags;
}

/**
 * @brief       Get event record id
 *
 * @param       er is a pointer to event record instance.
 *
 * @retval      Returns event record identifier.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
inline event_id_t event_record_get_id(const event_record_t *er)
{
    return er->id;
}

/**
 * @brief       Get event record type
 *
 * @param       er is a pointer to event record instance.
 *
 * @retval      Returns event record event type.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
inline int32_t event_record_get_type(const event_record_t *er)
{
    return er->type;
}

/**
 * @brief       Get event record number of defined DDM parameters.
 *
 * @param       er is a pointer to event record instance.
 *
 * @retval      Returns event record event DDM parameters.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 */
inline uint32_t event_record_get_data_size(const event_record_t *er)
{
    return er->data_size;
}

/**
 * @brief       Get event record DDM parameter at specified index.
 *
 * @param       er is a pointer to event record instance.
 *
 * @retval      Returns event record event DDM entry.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 * @pre         Parameter @a index must be smaller than the value returned by
 *              @ref event_record_get_data_size.
 */
inline const ddm_entry_t *event_record_get_parameter_data(const event_record_t *er, size_t index)
{
    return &er->data[index].parameter;
}

/**
 * @brief       Get event record trigger data at specified index.
 *
 * @param       er is a pointer to event record instance.
 *
 * @retval      Returns event record event trigger value.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 * @pre         Parameter @a index must be smaller than the value returned by
 *              @ref event_record_get_data_size.
 */
inline int32_t event_record_get_trigger_data(const event_record_t *er, size_t index)
{
    return er->data[index].trigger;
}

/**
 * @brief       Get event record data type at specified index.
 *
 * @param       er is a pointer to event record instance.
 *
 * @retval      Returns event record data type at specified index.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 * @pre         Parameter @a index must be smaller than the value returned by
 *              @ref event_record_get_data_size.
 */
inline int32_t event_record_get_data_type(const event_record_t *er, size_t index)
{
    return er->data[index].data_type;
}

/**
 * @brief       Is data element at given index a DDM parameter?
 *
 * @param       er is a pointer to event record instance.
 * @param       index is the index of data element to be checked.
 *
 * @return      true if data element at given index is a DDM parameter,
 *              false otherwise.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 * @pre         Parameter @a index must be smaller than the value returned by
 *              @ref event_record_get_data_size.
 */
inline bool event_record_is_data_parameter(const event_record_t *er, size_t index)
{
    return er->data[index].data_type == EVENT_RECORD_DATA_TYPE_PARAMETER;
}

/**
 * @brief       Is data element at given index a trigger?
 *
 * @param       er is a pointer to event record instance.
 * @param       index is the index of data element to be checked.
 *
 * @return      true if data element at given index is a trigger,
 *              false otherwise.
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 * @pre         Parameter @a index must be smaller than the value returned by
 *              @ref event_record_get_data_size.
 */
inline bool event_record_is_data_trigger(const event_record_t *er, size_t index)
{
    return er->data[index].data_type == EVENT_RECORD_DATA_TYPE_TRIGGER;
}

/**
 * @brief       Copy event record @a er into event record @a new_copy
 *
 * @param       from is a pointer to event record instance to be copied from
 *              (source).
 * @param       to is a pointer to event record instance which will contain the
 *              source data @a from (destination).
 *
 * @pre         Parameter @a er must be non-NULL pointer.
 * @pre         Parameter @a new_copy must be non-NULL pointer.
 */
void event_record_copy(const event_record_t *from, event_record_t *to);

#endif /* EVENT_RECORD_H_ */
