name: Pull Request Policy Actions

on:
  create:
  delete:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - develop

jobs:
  branch-naming-policy:
    name: Branch Naming Policy
    if: github.ref_type == 'branch' || github.event.pull_request
    uses: onedometic/dicm-actions/.github/workflows/branch_name.yml@develop
    with:
      key: 'ISE'
    secrets:
      token: ${{ secrets.ACTIONS }}
  pr-auto-assign-author:
    name: Pull Request Auto Assign
    if: github.event.pull_request
    uses: onedometic/dicm-actions/.github/workflows/pull_request_auto_assign.yml@develop
    secrets:
      token: ${{ secrets.ACTIONS }}
  pr-title-naming-policy:
    name: Pull Request Title Naming Policy
    if: github.event.pull_request
    uses: onedometic/dicm-actions/.github/workflows/pull_request_title_name.yml@develop
    with:
      key: 'ISE'
    secrets:
      token: ${{ secrets.ACTIONS }}
  pr-auto-label-policy:
    name: Pull Request Label Policy
    if: github.event.pull_request
    uses: onedometic/dicm-actions/.github/workflows/pull_request_auto_label.yml@develop
    secrets:
      token: ${{ secrets.ACTIONS }}
