name: Validation Policies for a DICM Application

on:
  pull_request:
    branches:
      - develop

jobs:
  check_clang_format:
    name: Clang Format Checker
    uses: onedometic/dicm-actions/.github/workflows/clang_format_check.yml@develop
    secrets:
      token: ${{ secrets.ACTIONS }}
