name: Excel to JSON

on:
  push:
    branches:
      - develop
    paths:
      - 'doc/Connectivity_parameters_under_work.xlsm'
  workflow_dispatch:
    inputs:
      featureBranch:
        description: 'Feature branch name'
        required: true
        default: 'feature/ddmParams-update'
      devBranch:
        description: 'dev branch name'
        required: true
        default: 'dev'

jobs:
  convert-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pylightxl

      - name: Convert Excel to JSON
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import warnings
            import pylightxl as xl
            import json
            
            PARAMS_FILE = 'Connectivity_parameters_under_work.xlsm'
            PARAMETERS = 'Parameters'
            TYPES = 'Types'
            ENUMS = 'Enums'
            # Ignore userWarings to avoid these warnings to appear at the console when opening excel file containing ddm parameters.
            warnings.filterwarnings("ignore", category=UserWarning)
            #gets the given excel file that has to be located in the same folder and returns it as a db
            def import_xls(file): 
                __location__ = os.path.realpath(
                    os.path.abspath(os.path.join(os.getcwd(), 'doc')))
                # readxl returns a pylightxl database that holds all worksheets and its data
                return xl.readxl(fn=os.path.join(__location__, file))
            #takes the corrspondng excel file of all the ddm parameters and parses it into a list of DDM_class clases
            def get_ddm_parameters():
                ddm_data = {}
                db = import_xls(PARAMS_FILE)
                # get total number of rows in the excel sheet
                total_rows = db.ws(ws=PARAMETERS).maxrow
                # for iteration over all the rows in the excel sheet.
                # on every row we will take the class name, porperty_name, parameter, and in/out_data_type
                for rowNum in range(2, total_rows+1):
                    class_name = db.ws(ws=PARAMETERS).address(address='D'+str(rowNum))
                    property_name = db.ws(ws=PARAMETERS).address(
                        address='G'+str(rowNum))
                    parameter = db.ws(ws=PARAMETERS).address(address='H'+str(rowNum))
                    # type = 'INT32_T'
                    writeable = 1
                    out_data_type = db.ws(ws=PARAMETERS).address(
                        address='M'+str(rowNum))
                    out_type = out_data_type.upper()
                    # if out_data_type == 'string': type = 'STRING'
                    in_data_type = db.ws(ws=PARAMETERS).address(
                        address='J'+str(rowNum))
                    in_type = in_data_type.upper()
                    if in_data_type == '-': writeable = 0
                    unit = db.ws(ws=PARAMETERS).address(
                        address='N'+str(rowNum))
                    factor = ''
                    types_total_rows = db.ws(ws=TYPES).maxrow
                    out_values = db.ws(ws=PARAMETERS).address(address='O'+str(rowNum))
                    if not unit == '-':
                        for types_rowNum in range(2, types_total_rows+1):
                            types_unit = db.ws(ws=TYPES).address(
                                address='D'+str(types_rowNum))
                            if unit == types_unit:
                                factor = db.ws(ws=TYPES).address(
                                address='G'+str(types_rowNum))
                    struct = None
                    if in_type == 'STRUCT' or out_type == 'STRUCT':
                        out_values = db.ws(ws=PARAMETERS).address(address='O'+str(rowNum))
                        for types_rowNum in range(2, types_total_rows+1):
                            types_def = db.ws(ws=TYPES).address(
                                address='O'+str(types_rowNum))
                            if out_values == types_def:
                                struct = db.ws(ws=TYPES).address(
                                    address='P'+str(types_rowNum))
                    enum_objects = None
                    if unit == 'enum' or unit == 'bitfield':
                        enum_label = db.ws(ws=PARAMETERS).address(address='O'+str(rowNum))
                        enums_total_rows = db.ws(ws=ENUMS).maxrow
                        for enums_rowNum in range(2, enums_total_rows+1):
                            enums_label = db.ws(ws=ENUMS).address(
                                address='A'+str(enums_rowNum))
                            if enum_label == enums_label:
                                enum_values =str(db.ws(ws=ENUMS).row(row=enums_rowNum))
                                enum_values = [value for value in db.ws(ws=ENUMS).row(row=enums_rowNum)[1:] if value != '']
                                enum_objects = []
                                for value in enum_values:
                                    key, val = value.split('=')
                                    enum_objects.append({"key": key.strip(), "value": val.strip()})
                    # # if the class_name is not empty, look if it's not in the ddm_data table
                    # # if not, create a new DDM_class object into it with the class_name as name
                    if len(class_name):
                        if not (class_name in ddm_data):
                            ddm_data[class_name] = {}
                        ddm_data[class_name][property_name] = {
                            key: value for key, value in {
                                "parameter": [int(parameter[6:8], 16), 'instance', int(parameter[2:4], 16), int(parameter[0:2], 16)],
                                "in_type": in_type,
                                "out_type": out_type,
                                "struct": struct,
                                "enum": enum_objects,
                                "unit": unit,
                                "factor": factor,
                                "writeable": writeable
                            }.items() if value is not None
                        }
                return ddm_data
            def convert_to_JSON(data, filename):
                with open(filename + '.json', 'w') as f:
                    json.dump(data, f)
            ddm_data = get_ddm_parameters()
            convert_to_JSON(ddm_data, 'ddmParams')
      # - name: Convert Excel to JSON
      #   run: python scripts/DDM_to_JSON.py

      - name: Checkout APP repo and feature branch
        uses: actions/checkout@v2
        with:
          repository: onedometic/app
          ref: feature/ddmParams-update
          token: ${{ secrets.ACTIONS_PUSH }}
          path: app

      - name: Copy JSON to app repo
        run: cp ddmParams.json app/src/core/connectivity/protocols/ddm2/ddmParams.json

      - name: Merge dev into feature branch within app repo
        run: |
          cd app
          git fetch origin ${{ github.event.inputs.devBranch }}
          git merge origin/${{ github.event.inputs.devBranch }} --no-edit --allow-unrelated-histories || {
            echo "Merge conflicts detected, attempting to resolve."
          }

      - name: Commit and push changes to the feature branch
        run: |
          cd app
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/core/connectivity/protocols/ddm2/ddmParams.json
          git commit -m "Update ddmParams.json"
          git push origin ${{ github.event.inputs.featureBranch }}
