name: Pull Request Title Naming Policy Action

on:
  pull_request:
    branches:
      - develop

jobs:
  pr-title-naming-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS }}
          submodules: recursive

      - name: Enforce Pull Request Title Naming Policy
        uses: ryanvade/enforce-pr-title-style-action@v2.1.2
        with:
          projectKey: 'ISE'
          keyAnywhereInTitle: false
