/*!
    \file miniddm_parameter_list.h
    \brief Dometic BLE Sensor Application layer definitions.

    MiniDDM parameter list defines
    GENERATED FILE, DO NOT EDIT!
    Exported from "Connectivity_parameters_under_work.xlsm"
        at: 2026-01-26 10:55:25 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
        by: Andreas Lundeen
*/

#ifndef MINIDDM_PARAMETER_LIST_H_
#define MINIDDM_PARAMETER_LIST_H_
#include <stdint.h>

#define MINIDDM_PARAMETER_LIST_SIZE 171
#define MINIDDM_SENSOR_LIST_SIZE 10
#define MINIDDM_SENSOR_NODE_LIST_SIZE 9

typedef enum MINIDDM_NODE_ENUM
{
    NODE_CLIMATE = 0x00,
    NODE_AIR_QUALITY = 0x01,
    NODE_DOOR = 0x02,
    NODE_MOTION = 0x03,
    NODE_WIRE_BREAK_AND_VOLTAGE = 0x04,
    NODE_TEST = 0x05,
    NODE_DIFFERENTIAL_PRESSURE = 0x06,
    NODE_DOOR_CLIMATE = 0x07,
    NODE_EXTENDED_SENSOR = 0x08,
} MINIDDM_NODE_ENUM;

typedef enum MINIDDM_SENSOR_ENUM
{
    SENSOR_NODE = 0x00,
    SENSOR_ACCELEROMETER = 0x01,
    SENSOR_HALL_SENSOR = 0x02,
    SENSOR_BME280 = 0x03,
    SENSOR_BME680 = 0x04,
    SENSOR_PIR_SENSOR = 0x05,
    SENSOR_WIRE_BREAK_SENSOR = 0x06,
    SENSOR_VOLTAGE_SENSOR = 0x07,
    SENSOR_DIFFERENTIAL_PRESSURE_SENSOR = 0x08,
    SENSOR_HALL_ANALOG_SENSOR = 0x09,
} MINIDDM_SENSOR_ENUM;

typedef enum MINIDDM_PARAM_ENUM
{
    PARAM_NODE_MANUFACTURER = 0x01,
    PARAM_NODE_PRODUCT_TYPE = 0x02,
    PARAM_NODE_NODE_TYPE = 0x03,
    PARAM_NODE_ID = 0x04,
    PARAM_NODE_NAME = 0x05,
    PARAM_NODE_FACTORY_RESET = 0x06,
    PARAM_NODE_ADVERTISING_INTERVAL = 0x07,
    PARAM_NODE_ADVERTISING_INTERVAL_CONNECTED = 0x08,
    PARAM_NODE_CONNECTION_INTERVAL = 0x09,
    PARAM_NODE_SLAVE_LATENCY = 0x0a,
    PARAM_NODE_GAP_SHA1_HASH = 0x0b,
    PARAM_NODE_CONFIG_BLOB = 0x0c,
    PARAM_NODE_FUNCTION = 0x0d,
    PARAM_NODE_LOCATION = 0x0e,
    PARAM_NODE_ENTER_OTA_DFU = 0x0f,
    PARAM_NODE_NONCONNECTABLE_CONNECTION_INTERVAL = 0x10,
    PARAM_NODE_CONNECTABLE_CONNECTION_INTERVAL = 0x11,
    PARAM_NODE_GAP_BLOB = 0x12,
    PARAM_NODE_UPDATE_ADVERTISE_INTERVAL = 0x13,
    PARAM_NODE_LED_BLINK = 0x14,
    PARAM_NODE_CONNECTABLE_CONNECTION_INTERVAL_WITH_WL = 0x15,
    PARAM_NODE_PEER_DELETE = 0x16,
    PARAM_NODE_SERIAL_NUMBER = 0x17,
    PARAM_NODE_MANUFACTURING_DATE = 0x18,
    PARAM_NODE_MANUFACTURER_NAME = 0x19,
    PARAM_NODE_PRODUCT = 0x1a,
    PARAM_NODE_SKU = 0x1b,
    PARAM_NODE_FIRMWARE_VERSION = 0x1c,
    PARAM_NODE_PCB = 0x1d,
    PARAM_NODE_BOM = 0x1e,
    PARAM_NODE_ITEM_DESCRIPTION = 0x1f,
    PARAM_NODE_MODEL_NUMBER = 0x20,
    PARAM_NODE_MODEL_NAME = 0x21,
    PARAM_NODE_EAN13 = 0x22,
    PARAM_NODE_BATTERY_VOLTAGE = 0x23,
    PARAM_NODE_EXTERNAL_POWER_SENSE = 0x24,
    PARAM_ACCELEROMETER_STATUS = 0x01,
    PARAM_ACCELEROMETER_FACTORY_RESET = 0x02,
    PARAM_ACCELEROMETER_VALUE_ACCEL_X = 0x03,
    PARAM_ACCELEROMETER_VALUE_ACCEL_Y = 0x04,
    PARAM_ACCELEROMETER_VALUE_ACCEL_Z = 0x05,
    PARAM_ACCELEROMETER_VALUE_LONGITUDINAL_TILT_ANGLE = 0x06,
    PARAM_ACCELEROMETER_VALUE_LATERAL_TILT_ANGLE = 0x07,
    PARAM_ACCELEROMETER_VALUE_TEMP = 0x08,
    PARAM_ACCELEROMETER_VALUE_WHOAMI = 0x09,
    PARAM_ACCELEROMETER_EVENT_ACCEL = 0x0a,
    PARAM_ACCELEROMETER_SEND_ACCEL_X = 0x0b,
    PARAM_ACCELEROMETER_SEND_ACCEL_Y = 0x0c,
    PARAM_ACCELEROMETER_SEND_ACCEL_Z = 0x0d,
    PARAM_ACCELEROMETER_SEND_TILT_ANGLE = 0x0e,
    PARAM_ACCELEROMETER_SEND_TEMP = 0x0f,
    PARAM_ACCELEROMETER_SAMPLING_PERIOD = 0x10,
    PARAM_ACCELEROMETER_CAL_FLAT_DONE = 0x11,
    PARAM_ACCELEROMETER_CAL_FLAT_START = 0x12,
    PARAM_ACCELEROMETER_CAL_TILT_DONE = 0x13,
    PARAM_ACCELEROMETER_CAL_TILT_START = 0x14,
    PARAM_ACCELEROMETER_CAL_TILT_POSITION = 0x15,
    PARAM_ACCELEROMETER_SET_DATA_RATE = 0x16,
    PARAM_ACCELEROMETER_SET_POWER_MODE = 0x17,
    PARAM_ACCELEROMETER_SET_FILTER_BANDWIDTH = 0x18,
    PARAM_ACCELEROMETER_SET_FULL_SCALE = 0x19,
    PARAM_ACCELEROMETER_SET_FILTER_PATH = 0x1a,
    PARAM_ACCELEROMETER_SET_6D_THRESHOLD = 0x1b,
    PARAM_ACCELEROMETER_SET_TAP_THRHLD_X = 0x1c,
    PARAM_ACCELEROMETER_SET_TAP_THRHLD_Y = 0x1d,
    PARAM_ACCELEROMETER_SET_TAP_THRHLD_Z = 0x1e,
    PARAM_ACCELEROMETER_SET_TAP_RECG_AXIS = 0x1f,
    PARAM_ACCELEROMETER_SET_TAP_AXIS_PRIORITY = 0x20,
    PARAM_ACCELEROMETER_SET_FF_THRESHOLD = 0x21,
    PARAM_ACCELEROMETER_SET_FF_DURATION = 0x22,
    PARAM_ACCELEROMETER_SET_WKUP_THRESHOLD = 0x23,
    PARAM_ACCELEROMETER_SET_WKUP_DURATION = 0x24,
    PARAM_ACCELEROMETER_SET_DT_DURATION = 0x25,
    PARAM_ACCELEROMETER_SET_DT_QUIET_TIME = 0x26,
    PARAM_ACCELEROMETER_SET_DT_SHOCK_DURATION = 0x27,
    PARAM_ACCELEROMETER_SET_TAP_MODE = 0x28,
    PARAM_ACCELEROMETER_SET_TAP_RECOGN_X = 0x29,
    PARAM_ACCELEROMETER_SET_TAP_RECOGN_Y = 0x2a,
    PARAM_ACCELEROMETER_SET_TAP_RECOGN_Z = 0x2b,
    PARAM_ACCELEROMETER_SINGLE_TAP_ENABLE = 0x2c,
    PARAM_ACCELEROMETER_DOUBLE_TAP_ENABLE = 0x2d,
    PARAM_ACCELEROMETER_FREEFALL_ENABLE = 0x2e,
    PARAM_ACCELEROMETER_TILT_ENABLE = 0x2f,
    PARAM_ACCELEROMETER_WAKEUP_ENABLE = 0x30,
    PARAM_HALL_SENSOR_STATUS = 0x01,
    PARAM_HALL_SENSOR_FACTORY_RESET = 0x02,
    PARAM_HALL_SENSOR_OPEN = 0x03,
    PARAM_HALL_SENSOR_SEND_OPEN = 0x04,
    PARAM_BME280_STATUS = 0x01,
    PARAM_BME280_FACTORY_RESET = 0x02,
    PARAM_BME280_TEMPERATURE = 0x03,
    PARAM_BME280_HUMIDITY = 0x04,
    PARAM_BME280_PRESSURE = 0x05,
    PARAM_BME280_SEND_TEMPERATURE = 0x06,
    PARAM_BME280_SEND_HUMIDITY = 0x07,
    PARAM_BME280_SEND_PRESSURE = 0x08,
    PARAM_BME280_OVERSAMPLING_TEMPERATURE = 0x09,
    PARAM_BME280_OVERSAMPLING_HUMIDITY = 0x0a,
    PARAM_BME280_OVERSAMPLING_PRESSURE = 0x0b,
    PARAM_BME280_SAMPLING_PERIOD = 0x0c,
    PARAM_BME680_STATUS = 0x01,
    PARAM_BME680_FACTORY_RESET = 0x02,
    PARAM_BME680_TEMPERATURE = 0x03,
    PARAM_BME680_HUMIDITY = 0x04,
    PARAM_BME680_PRESSURE = 0x05,
    PARAM_BME680_GAS = 0x06,
    PARAM_BME680_AIR_QUALITY = 0x07,
    PARAM_BME680_IAQ = 0x08,
    PARAM_BME680_CO2 = 0x09,
    PARAM_BME680_VOC = 0x0a,
    PARAM_BME680_STABILIZATION_STATUS = 0x0b,
    PARAM_BME680_RUN_IN_STATUS = 0x0c,
    PARAM_BME680_SEND_TEMPERATURE = 0x0d,
    PARAM_BME680_SEND_HUMIDITY = 0x0e,
    PARAM_BME680_SEND_PRESSURE = 0x0f,
    PARAM_BME680_SEND_GAS = 0x10,
    PARAM_BME680_SEND_AIR_QUALITY = 0x11,
    PARAM_BME680_SEND_IAQ = 0x12,
    PARAM_BME680_SEND_CO2 = 0x13,
    PARAM_BME680_SEND_VOC = 0x14,
    PARAM_BME680_SEND_STABILIZATION_STATUS = 0x15,
    PARAM_BME680_SEND_RUN_IN_STATUS = 0x16,
    PARAM_BME680_SAMPLE_RATE = 0x17,
    PARAM_BME680_SAMPLE_RATE_GAS = 0x18,
    PARAM_PIR_SENSOR_STATUS = 0x01,
    PARAM_PIR_SENSOR_FACTORY_RESET = 0x02,
    PARAM_PIR_SENSOR_EVENT = 0x03,
    PARAM_PIR_SENSOR_SEND_EVENT = 0x04,
    PARAM_WIRE_BREAK_SENSOR_STATUS = 0x01,
    PARAM_WIRE_BREAK_SENSOR_FACTORY_RESET = 0x02,
    PARAM_WIRE_BREAK_SENSOR_SUB_FUNCTION = 0x03,
    PARAM_WIRE_BREAK_SENSOR_SUB_LOCATION = 0x04,
    PARAM_WIRE_BREAK_SENSOR_OPEN = 0x05,
    PARAM_WIRE_BREAK_SENSOR_ADC_OPEN = 0x06,
    PARAM_WIRE_BREAK_SENSOR_SEND_OPEN = 0x07,
    PARAM_WIRE_BREAK_SENSOR_SEND_ADC = 0x08,
    PARAM_WIRE_BREAK_SENSOR_SAMPLING_PERIOD = 0x09,
    PARAM_VOLTAGE_SENSOR_STATUS = 0x01,
    PARAM_VOLTAGE_SENSOR_FACTORY_RESET = 0x02,
    PARAM_VOLTAGE_SENSOR_SUB_FUNCTION = 0x03,
    PARAM_VOLTAGE_SENSOR_SUB_LOCATION = 0x04,
    PARAM_VOLTAGE_SENSOR_ADC_12V = 0x05,
    PARAM_VOLTAGE_SENSOR_ADC_BATT = 0x06,
    PARAM_VOLTAGE_SENSOR_ADC_BILGE = 0x07,
    PARAM_VOLTAGE_SENSOR_VOUT_SENSE = 0x08,
    PARAM_VOLTAGE_SENSOR_POWER_STATUS = 0x09,
    PARAM_VOLTAGE_SENSOR_SEND_ADC_12V = 0x0a,
    PARAM_VOLTAGE_SENSOR_SEND_ADC_BATT = 0x0b,
    PARAM_VOLTAGE_SENSOR_SEND_ADC_BILGE = 0x0c,
    PARAM_VOLTAGE_SENSOR_SEND_VOUT_SENSE = 0x0d,
    PARAM_VOLTAGE_SENSOR_SAMPLING_PERIOD = 0x0e,
    PARAM_DIFFERENTIAL_PRESSURE_SENSOR_STATUS = 0x01,
    PARAM_DIFFERENTIAL_PRESSURE_SENSOR_FACTORY_RESET = 0x02,
    PARAM_DIFFERENTIAL_PRESSURE_SENSOR_DIFFERENTIAL_PRESSURE = 0x03,
    PARAM_DIFFERENTIAL_PRESSURE_SENSOR_TEMPERATURE = 0x04,
    PARAM_DIFFERENTIAL_PRESSURE_SENSOR_PRODUCT_IDENTIFIER = 0x05,
    PARAM_DIFFERENTIAL_PRESSURE_SENSOR_SEND_DIFFERENTIAL_PRESSURE = 0x06,
    PARAM_DIFFERENTIAL_PRESSURE_SENSOR_SEND_TEMPERATURE = 0x07,
    PARAM_DIFFERENTIAL_PRESSURE_SENSOR_SAMPLING_PERIOD = 0x08,
    PARAM_DIFFERENTIAL_PRESSURE_SENSOR_MEASUREMENT_COMMAND = 0x09,
    PARAM_HALL_ANALOG_SENSOR_STATUS = 0x01,
    PARAM_HALL_ANALOG_SENSOR_FACTORY_RESET = 0x02,
    PARAM_HALL_ANALOG_SENSOR_VALUE_MAGNETIC_FIELD_X = 0x03,
    PARAM_HALL_ANALOG_SENSOR_VALUE_MAGNETIC_FIELD_Y = 0x04,
    PARAM_HALL_ANALOG_SENSOR_VALUE_MAGNETIC_FIELD_Z = 0x05,
    PARAM_HALL_ANALOG_SENSOR_EVENT = 0x06,
    PARAM_HALL_ANALOG_SENSOR_SEND_MAG_FIELD_X = 0x07,
    PARAM_HALL_ANALOG_SENSOR_SEND_MAG_FIELD_Y = 0x08,
    PARAM_HALL_ANALOG_SENSOR_SEND_MAG_FIELD_Z = 0x09,
    PARAM_HALL_ANALOG_SENSOR_SEND_EVENT = 0x0a,
    PARAM_HALL_ANALOG_SENSOR_SAMPLING_PERIOD = 0x0b,
} MINIDDM_PARAM_ENUM;

typedef enum MINIDDM_TYPE_ENUM
{
    MINIDDM_TYPE_U8,
    MINIDDM_TYPE_U16,
    MINIDDM_TYPE_U32,
    MINIDDM_TYPE_STRING,
    MINIDDM_TYPE_BINARY,
    MINIDDM_TYPE_VOID,
    MINIDDM_TYPE_CELSIUS_2,
    MINIDDM_TYPE_PERCENT_2,
    MINIDDM_TYPE_PASCAL_4,
    MINIDDM_TYPE_OHM_4,
    MINIDDM_TYPE_G_2,
    MINIDDM_TYPE_VOLT_2,
    MINIDDM_TYPE_SECONDS_4,
    MINIDDM_TYPE_SECONDS_2,
    MINIDDM_TYPE_DEGREES_2,
    MINIDDM_TYPE_I8,
    MINIDDM_TYPE_I16,
    MINIDDM_TYPE_I32,
    MINIDDM_TYPE_MILLITESLA_2,
    MINIDDM_TYPE_COUNT,
} MINIDDM_TYPE_ENUM;

typedef struct MINIDDM_SENSOR_NODE_LIST
{
    int sensor_count;
    uint8_t *sensor_list;
} MINIDDM_SENSOR_NODE_LIST;

typedef struct MINIDDM_SENSOR_LIST
{
    int parameter_count;
    int parameter_start;
} MINIDDM_SENSOR_LIST;

typedef struct MINIDDM_PARAMETER_LIST
{
    int parameter_id;
    MINIDDM_TYPE_ENUM type;
} MINIDDM_PARAMETER_LIST;

extern const int Miniddm_size_list[MINIDDM_TYPE_COUNT + 1];
extern const int Miniddm_factor_list[MINIDDM_TYPE_COUNT + 1];
extern const MINIDDM_SENSOR_NODE_LIST Miniddm_sensor_node_list[MINIDDM_SENSOR_NODE_LIST_SIZE];
extern const MINIDDM_SENSOR_LIST Miniddm_sensor_list[MINIDDM_SENSOR_LIST_SIZE];
extern const MINIDDM_PARAMETER_LIST Miniddm_parameter_list[MINIDDM_PARAMETER_LIST_SIZE];


#endif /* MINIDDM_PARAMETER_LIST_H_ */
