# DICMFramworkDefaults configuration
list (APPEND EXCLUDE_HMI_DATA_SOURCES "")

set (FRAMEWORK_MODULES "")
# Core connectors and services
option(CONFIG_CONNECTOR_BLE "Enable to include BLE connector" ON)
option(CONFIG_CONNECTOR_WIFI "Enable to include WIFI connector" ON)
option(CONFIG_CONNECTOR_UART "Enable to include UART connector" OFF)
option(CONFIG_CONNECTOR_LINDEV "Enable to include LINDEV connector" ON)
option(CONFIG_CONNECTOR_LIN_SERVER "Enable to include LIN Server connector" OFF)
option(CONFIG_CONNECTOR_MQTT "Enable to include MQTT connector" ON)
option(CONFIG_CONNECTOR_PREM_RVC "Enable to include PREM_RVC connector" OFF)
option(CONFIG_CONNECTOR_RVC "Enable to include RVC connector" ON)
option(CONFIG_CONNECTOR_SYSTEM "Enable to include SYSTEM connector" ON)
option(CONFIG_CONNECTOR_SYSAPPL_SERVICE "Enable to include System Application service" ON)
option(CONFIG_CONNECTOR_USM "Enable to include USM connector" ON)
option(CONFIG_CONNECTOR_US_DICM "Enable to include US_DICM connector" ON)
option(CONFIG_CONNECTOR_HMI "Enable to include HMI connector" OFF)
option(CONFIG_CONNECTOR_DEVICE_DISCOVERY "Enable device discovery/MDSN server" ON)
option(CONFIG_CONNECTOR_EVENT_NOTIFICATION "Enable Event Notification connector" OFF)
option(CONFIG_CONNECTOR_DDM_LOG "Enable DDM log connector" OFF)
option(CONFIG_CONNECTOR_FULL_CLIMATE_RULE_ENGINE "Enable Full Climate (Rule Engine) connector" OFF)
option(CONFIG_CONNECTOR_SMART_ECO_RULE_ENGINE "Enable Smart Eco (Rule Engine) connector" OFF)
option(CONFIG_CONNECTOR_IOT_MODEM "Enable IOT modem connector" OFF)
option(CONFIG_CONNECTOR_UART_DDM "Enable to include UART DDM connector" OFF)
option(CONFIG_CONNECTOR_BATT_MGMT_SERVICE "Enable to include Battery Management service" OFF)
option(CONFIG_CONNECTOR_IC_MGMT_SERVICE "Enable to include Inverter Charger Management service" OFF)
option(CONFIG_CONNECTOR_NFC "Enable to include NFC connector service" OFF)
option(CONFIG_CONNECTOR_NMEA2K "Enable to include Nmea2k connector service" OFF)
option(CONFIG_CONNECTOR_CLIMATE_ZONE_FEATURE "Enable to include Climate zone feature service" ON)
option(CONFIG_CONNECTOR_SMART_ECO_FEATURE "Enable to include Smart ECO feature service" ON)
option(CONFIG_CONNECTOR_FEATURE_MGR "Enable to include Feature mgr service" ON)
option(CONFIG_CONNECTOR_PROD_SNIFFER_SERVICE "Enable to include Product Sniffer service" OFF)
option(CONFIG_CONNECTOR_RS485_MASTER "Enable to include RS485 master connector" OFF)

# Flash size
option(CONFIG_FLASHSIZE_8MB "Build for 8MB flash size, default to 4MB" OFF)

# Platform Security
option(CONFIG_CONNECTOR_WIFI_SERVICE_ON_AP_ONLY "Only enable DDM2 socket services to start on AP mode" OFF)
option(CONFIG_SECURE_PLATFORM_DEVELOPMENT "Enable to include Secure Platform during development" OFF)
option(CONFIG_SECURE_PLATFORM_PRODUCTION "Enable to include Secure Platform for production" OFF)
option(CONFIG_NO_SECURE_PLATFORM_LEGACY_BOOT_KEY "Enable to build with no Secure Platform using legacy boot key" OFF)
option(CONFIG_CONNECTOR_TLS "Enable to include TLS connector" OFF)
option(CONFIG_DEVELOPMENT_VIRTUAL_EFUSE "Enable to include Platform development with virtual eFuse" OFF)

# Core services
option(CONFIG_LOG_SERVICE "Enable to include Log service" ON)
option(CONFIG_LOG_SERVICE_WEB_SERVER "Enable to include a http based web log service" ON)
option(CONFIG_POWER_MANAGEMENT "Enable to include power management" OFF)
option(CONFIG_CONNECTOR_SUPERVISOR "Enable to include Supervisor service" OFF)

option(CONFIG_CONNECTOR_BZ_SERVICE "Enable Buzzer Service connector" OFF)
option(CONFIG_CONNECTOR_ACCELEROMETER "Enable to include Accelerometer connector" OFF)
option(CONFIG_CONNECTOR_SIMULATOR_INVENTILATE "Enable Inventilate software simulator connector" OFF)
option(CONFIG_CONNECTOR_SIMULATOR_SHARC "Enable Sharc software simulator connector" OFF)
option(CONFIG_CONNECTOR_SIMULATOR_SHAPE "Enable Shape software simulator connector" OFF)
option(CONFIG_CONNECTOR_SIMULATOR_CFX2 "Enable CFX2 software simulator connector" OFF)
option(CONFIG_CONNECTOR_SIMULATOR_SHAPEX "Enable SHAPEX software simulator connector" OFF)
option(CONFIG_CONNECTOR_SIMULATOR_EVENT_NOTIFICATION "Enable Event Notification software simulator connector" OFF)
option(CONFIG_CONNECTOR_SIMULATOR_THUNDERSTORM "Enable Thunderstorm software simulator connector" OFF)
option(CONFIG_CONNECTOR_SIMULATOR_PROD_MBAT "Enable Battery mbat software simulator connector" OFF)

option(CONFIG_CONNECTOR_UNITTEST "Enable UnitTest connector" OFF)

# possible core connectors and services
option(CONFIG_CONNECTOR_RCS "Enable to include RCS connector" OFF)
option(CONFIG_CONNECTOR_LIGHT "Enable Light connector" OFF)

# Not implemented yet
option(CONFIG_CONNECTOR_PMIC "Enable Battery Service PMIC BQ25895 connector" OFF)
option(CONFIG_CONNECTOR_GNSS "Enable to include GNSS connector" OFF)
option(CONFIG_CONNECTOR_TESLA "Enable to include TESLA connector" OFF)
option(CONFIG_CONNECTOR_MODEM "Enable to include MODEM connector" OFF)  # To be removed?? Not used anywhere?
option(CONFIG_CONNECTOR_SENSORS "Enable to include SENSORS connector" OFF)

# HMI build options
option(CONFIG_BUILD_HMI_DATA "Enable building for extracting the hmi_data partition" OFF)
if (CONFIG_BUILD_HMI_DATA)
    message(STATUS "Building for extracting the hmi_data partition")
endif()

option(MIC_BUILD_PRODUCTION_ENVIRONMENT "Build for cloud production environment" OFF)
if (MIC_BUILD_PRODUCTION_ENVIRONMENT)
    message(STATUS "Building for cloud production environment")
    add_compile_definitions(MIC_BUILD_PRODUCTION_ENVIRONMENT)
    list (APPEND FRAMEWORK_MODULES MIC_BUILD_PRODUCTION_ENVIRONMENT)
else()
    message(STATUS "Building for cloud test environment")
endif()

if (CONFIG_CONNECTOR_BLE)
add_compile_definitions(CONNECTOR_BLE)
list (APPEND FRAMEWORK_MODULES CONNECTOR_BLE)
endif()
if (CONFIG_CONNECTOR_WIFI)
add_compile_definitions(CONNECTOR_WIFI)
list (APPEND FRAMEWORK_MODULES CONNECTOR_WIFI)
endif()
if (CONFIG_CONNECTOR_PREM_RVC)
add_compile_definitions(CONNECTOR_PREM_RVC)
list (APPEND FRAMEWORK_MODULES CONNECTOR_PREM_RVC)
endif()
if (CONFIG_CONNECTOR_RVC)
add_compile_definitions(CONNECTOR_RVC)
list (APPEND FRAMEWORK_MODULES CONNECTOR_RVC)
endif()
if (CONFIG_CONNECTOR_UART)
add_compile_definitions(CONNECTOR_UART)
list (APPEND FRAMEWORK_MODULES CONNECTOR_UART)
endif()
if (CONFIG_CONNECTOR_UART_DDM)
add_compile_definitions(CONNECTOR_UART_DDM)
list (APPEND FRAMEWORK_MODULES CONNECTOR_UART_DDM)
endif()
if (CONFIG_CONNECTOR_HMI)
add_compile_definitions(CONNECTOR_HMI)
list (APPEND FRAMEWORK_MODULES CONNECTOR_HMI)
endif()
if (CONFIG_CONNECTOR_DEVICE_DISCOVERY)
add_compile_definitions(CONNECTOR_DEVICE_DISCOVERY)
list (APPEND FRAMEWORK_MODULES CONNECTOR_DEVICE_DISCOVERY)
endif()
if (CONFIG_CONNECTOR_EVENT_NOTIFICATION)
add_compile_definitions(CONNECTOR_EVENT_NOTIFICATION)
list (APPEND FRAMEWORK_MODULES CONNECTOR_EVENT_NOTIFICATION)
endif()
if (CONFIG_CONNECTOR_LINDEV)
add_compile_definitions(CONNECTOR_LINDEV)
list (APPEND FRAMEWORK_MODULES CONNECTOR_LINDEV)
endif()
if (CONFIG_CONNECTOR_MQTT)
add_compile_definitions(CONNECTOR_MQTT)
list (APPEND FRAMEWORK_MODULES CONNECTOR_MQTT)
endif()
if (CONFIG_CONNECTOR_USM)
add_compile_definitions(CONNECTOR_USM)
list (APPEND FRAMEWORK_MODULES CONNECTOR_USM)
endif()
if (CONFIG_CONNECTOR_US_DICM)
add_compile_definitions(CONNECTOR_US_DICM)
list (APPEND FRAMEWORK_MODULES CONNECTOR_US_DICM)
endif()
if (CONFIG_CONNECTOR_SYSTEM)
add_compile_definitions(CONNECTOR_SYSTEM)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SYSTEM)
endif()
if (CONFIG_CONNECTOR_SYSAPPL_SERVICE)
add_compile_definitions(CONNECTOR_SYSAPPL_SERVICE)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SYSAPPL_SERVICE)
endif()
if (CONFIG_CONNECTOR_BATT_MGMT_SERVICE)
add_compile_definitions(CONNECTOR_BATT_MGMT_SERVICE)
list (APPEND FRAMEWORK_MODULES CONNECTOR_BATT_MGMT_SERVICE)
endif()
if (CONFIG_CONNECTOR_IC_MGMT_SERVICE)
add_compile_definitions(CONNECTOR_IC_MGMT_SERVICE)
list (APPEND FRAMEWORK_MODULES CONNECTOR_IC_MGMT_SERVICE)
endif()
if (CONFIG_CONNECTOR_CLIMATE_ZONE_FEATURE)
add_compile_definitions(CONNECTOR_CLIMATE_ZONE_FEATURE)
list (APPEND FRAMEWORK_MODULES CONNECTOR_CLIMATE_ZONE_FEATURE)
endif()
if (CONFIG_CONNECTOR_SMART_ECO_FEATURE)
add_compile_definitions(CONNECTOR_SMART_ECO_FEATURE)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SMART_ECO_FEATURE)
endif()
if (CONFIG_CONNECTOR_FEATURE_MGR)
add_compile_definitions(CONNECTOR_FEATURE_MGR)
endif()
if (CONFIG_CONNECTOR_PROD_SNIFFER_SERVICE)
add_compile_definitions(CONNECTOR_PROD_SNIFFER_SERVICE)
endif()
if (CONFIG_CONNECTOR_DDM_LOG)
add_compile_definitions(CONNECTOR_DDM_LOG)
list (APPEND FRAMEWORK_MODULES CONNECTOR_DDM_LOG)
endif()
if (CONFIG_CONNECTOR_FULL_CLIMATE_RULE_ENGINE)
add_compile_definitions(CONNECTOR_FULL_CLIMATE_RULE_ENGINE)
list (APPEND FRAMEWORK_MODULES CONNECTOR_FULL_CLIMATE_RULE_ENGINE)
endif()
if (CONFIG_CONNECTOR_SMART_ECO_RULE_ENGINE)
add_compile_definitions(CONNECTOR_SMART_ECO_RULE_ENGINE)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SMART_ECO_RULE_ENGINE)
endif()
if (CONFIG_CONNECTOR_NFC)
add_compile_definitions(CONNECTOR_NFC)
list (APPEND FRAMEWORK_MODULES CONNECTOR_NFC)
endif()
if (CONFIG_CONNECTOR_NMEA2K)
add_compile_definitions(CONNECTOR_NMEA2K)
list (APPEND FRAMEWORK_MODULES CONNECTOR_NMEA2K)
endif()

if (CONFIG_CONNECTOR_IOT_MODEM)
add_compile_definitions(CONNECTOR_IOT_MODEM)
list (APPEND FRAMEWORK_MODULES CONNECTOR_IOT_MODEM)
endif()

if (CONFIG_SECURE_PLATFORM_PRODUCTION)
add_compile_definitions(SECURE_PLATFORM_PRODUCTION)
message(STATUS "Building with Secure Platform Enabled (production)")
set(CONFIG_CONNECTOR_TLS ON CACHE BOOL "Enable TLS Connector")
# For now we cannot allow a webserver until it is fully using tls
set(CONFIG_LOG_SERVICE_WEB_SERVER OFF CACHE BOOL "Enable to include a http based web log service" FORCE)
endif()
if (CONFIG_SECURE_PLATFORM_DEVELOPMENT)
message(STATUS "Building with Secure Platform Enabled (development)")
set(CONFIG_CONNECTOR_TLS ON CACHE BOOL "Enable TLS Connector")
endif()

if (CONFIG_CONNECTOR_TLS)
# if TLS is running we don't need to limit the service to only AP
set(CONFIG_CONNECTOR_WIFI_SERVICE_ON_AP_ONLY OFF CACHE BOOL "Only enable DDM2 socket services to start on AP mode")
add_compile_definitions(CONNECTOR_TLS)
list (APPEND FRAMEWORK_MODULES CONNECTOR_TLS)
endif()

if (CONFIG_CONNECTOR_WIFI_SERVICE_ON_AP_ONLY)
message(STATUS "Building with DDM2 socket services to start only on AP mode")
add_compile_definitions(CONNECTOR_WIFI_SERVICE_ON_AP_ONLY)
endif()
if (CONFIG_LOG_SERVICE)
add_compile_definitions(CONFIG_LOG_SERVICE)
endif()
if (${IDF_TARGET} STREQUAL "linux")
set(CONFIG_LOG_SERVICE_WEB_SERVER OFF CACHE BOOL "Enable to include a http based web log service" FORCE)
endif()
if (CONFIG_LOG_SERVICE AND CONFIG_LOG_SERVICE_WEB_SERVER)
add_compile_definitions(CONFIG_LOG_SERVICE_WEB_SERVER)
endif()

if (CONFIG_CONNECTOR_SUPERVISOR)
add_compile_definitions(CONNECTOR_SUPERVISOR)
endif()

if (CONFIG_POWER_MANAGEMENT)
add_compile_definitions(CONFIG_POWER_MANAGEMENT)
endif()

########################################################################
if (CONFIG_CONNECTOR_RCS)
add_compile_definitions(CONNECTOR_RCS)
list (APPEND FRAMEWORK_MODULES CONNECTOR_RCS)
endif()

if (CONFIG_CONNECTOR_LIGHT)
add_compile_definitions(CONNECTOR_LIGHT)
list (APPEND FRAMEWORK_MODULES CONNECTOR_LIGHT)
endif()

if (CONFIG_CONNECTOR_LIN_SERVER)
add_compile_definitions(CONNECTOR_LIN_SERVER)
list (APPEND FRAMEWORK_MODULES CONNECTOR_LIN_SERVER)
endif()
if (CONFIG_CONNECTOR_BATTERY_SERVICE)
add_compile_definitions(CONNECTOR_BATTERY_SERVICE)
list (APPEND FRAMEWORK_MODULES CONNECTOR_BATTERY_SERVICE)
endif()
if (CONFIG_CONNECTOR_DEVSIM)
add_compile_definitions(CONNECTOR_DEVSIM)
list (APPEND FRAMEWORK_MODULES CONNECTOR_DEVSIM)
endif()
if (CONFIG_CONNECTOR_RS485_MASTER)
add_compile_definitions(CONNECTOR_RS485_MASTER)
list (APPEND FRAMEWORK_MODULES CONNECTOR_RS485_MASTER)
endif()
if (CONFIG_CONNECTOR_BTS)
add_compile_definitions(CONNECTOR_BTS)
list (APPEND FRAMEWORK_MODULES CONNECTOR_BTS)
endif()
if (CONFIG_CONNECTOR_TMS)
add_compile_definitions(CONNECTOR_TMS)
list (APPEND FRAMEWORK_MODULES CONNECTOR_TMS)
endif()
if (CONFIG_CONNECTOR_BSS)
add_compile_definitions(CONNECTOR_BSS)
list (APPEND FRAMEWORK_MODULES CONNECTOR_BSS)
endif()

if (CONFIG_CONNECTOR_MODEM)
add_compile_definitions(CONNECTOR_MODEM)
list (APPEND FRAMEWORK_MODULES CONNECTOR_MODEM)
endif()
if (CONFIG_CONNECTOR_PMIC)
add_compile_definitions(CONNECTOR_PMIC)
list (APPEND FRAMEWORK_MODULES CONNECTOR_PMIC)
endif()
if (CONFIG_CONNECTOR_ACCELEROMETER)
add_compile_definitions(CONNECTOR_CONNECTOR_ACCELEROMETER)
list (APPEND FRAMEWORK_MODULES CONNECTOR_ACCELEROMETER)
endif()
if (CONFIG_CONNECTOR_BZ_SERVICE)
add_compile_definitions(CONNECTOR_BZ_SERVICE)
list (APPEND FRAMEWORK_MODULES CONNECTOR_BZ_SERVICE)
endif()
if (CONFIG_CONNECTOR_SIMULATOR_INVENTILATE)
add_compile_definitions(CONNECTOR_SIMULATOR_INVENTILATE)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SIMULATOR_INVENTILATE)
endif()
if (CONFIG_CONNECTOR_SIMULATOR_SHARC)
add_compile_definitions(CONNECTOR_SIMULATOR_SHARC)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SIMULATOR_SHARC)
endif()
if (CONFIG_CONNECTOR_SIMULATOR_SHAPE)
add_compile_definitions(CONNECTOR_SIMULATOR_SHAPE)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SIMULATOR_SHAPE)
endif()
if (CONFIG_CONNECTOR_SIMULATOR_CFX2)
add_compile_definitions(CONNECTOR_SIMULATOR_CFX2 SOFTWARE_SIMULATOR_CFX2)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SIMULATOR_CFX2)
endif()
if (CONFIG_CONNECTOR_SIMULATOR_SHAPEX)
add_compile_definitions(CONNECTOR_SIMULATOR_SHAPEX SOFTWARE_SIMULATOR_SHAPEX)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SIMULATOR_SHAPEX)
endif()
if (CONFIG_CONNECTOR_SIMULATOR_EVENT_NOTIFICATION)
add_compile_definitions(CONNECTOR_SIMULATOR_SHAPE CONNECTOR_SIMULATOR_RULE SOFTWARE_SIMULATOR_EVENT_NOTIFICATION)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SIMULATOR_EVENT_NOTIFICATION)
endif()
if (CONFIG_CONNECTOR_SIMULATOR_THUNDERSTORM)
add_compile_definitions(CONNECTOR_SIMULATOR_THUNDERSTORM SOFTWARE_SIMULATOR_THUNDERSTORM)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SIMULATOR_THUNDERSTORM)
endif()
if (CONFIG_CONNECTOR_SIMULATOR_PROD_MBAT)
add_compile_definitions(CONNECTOR_SIMULATOR_PROD_MBAT SOFTWARE_SIMULATOR_PROD_MBAT)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SIMULATOR_PROD_MBAT)
endif()

if (CONFIG_CONNECTOR_TESLA)
add_compile_definitions(CONNECTOR_TESLA)
list (APPEND FRAMEWORK_MODULES CONNECTOR_TESLA)
endif()

if (CONFIG_CONNECTOR_SENSORS)
add_compile_definitions(CONNECTOR_SENSORS)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SENSORS)
endif()
if (CONFIG_CONNECTOR_GNSS)
add_compile_definitions(CONNECTOR_GNSS)
list (APPEND FRAMEWORK_MODULES CONNECTOR_GNSS)
endif()
if (CONFIG_CONNECTOR_TEMPLATE)
add_compile_definitions(CONNECTOR_TEMPLATE)
list (APPEND FRAMEWORK_MODULES CONNECTOR_TEMPLATE)
endif()
if (CONFIG_CONNECTOR_SIMABM3)
add_compile_definitions(CONNECTOR_SIMABM3)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SIMABM3)
endif()
if (CONFIG_CONNECTOR_SIMMGW)
add_compile_definitions(CONNECTOR_SIMMGW)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SIMMGW)
endif()
if (CONFIG_CONNECTOR_SHAPE_SIM)
add_compile_definitions(CONNECTOR_SHAPE_SIM)
list (APPEND FRAMEWORK_MODULES CONNECTOR_SHAPE_SIM)
endif()

if (CONFIG_CONNECTOR_DCP_UART)
add_compile_definitions(CONNECTOR_DCP_UART)
list (APPEND FRAMEWORK_MODULES CONNECTOR_DCP_UART)
endif()

if (CONFIG_CONNECTOR_UNITTEST)
add_compile_definitions(CONNECTOR_UNITTEST)
list (APPEND FRAMEWORK_MODULES CONNECTOR_UNITTEST)
endif()

#    list(APPEND compile_definitions "-D_GNU_SOURCE")
#    list(APPEND compile_options     "-ffunction-sections"
#                                    "-fdata-sections"
#                                    "-fstrict-volatile-bitfields"
#                                    # warning-related flags
#                                    "-Wall"
#                                    "-Werror=all"
#                                    "-Wno-error=unused-function"
#                                    "-Wno-error=unused-but-set-variable"
#                                    "-Wno-error=unused-variable"
#                                    "-Wno-error=deprecated-declarations"
#                                    "-Wextra"
#                                    "-Wno-unused-parameter"
#                                    "-Wno-sign-compare"
#                                    # always generate debug symbols (even in release mode, these don't
#                                    # go into the final binary so have no impact on size
#                                    "-ggdb")
#
#    list(APPEND c_compile_options   "-std=gnu99"
#                                    "-Wno-old-style-declaration")
#
#    list(APPEND cxx_compile_options "-std=gnu++11")
list(APPEND EXTRA_COMPILER_OPTIONS "")

# select same as IDF
if (${IDF_TARGET} STREQUAL "linux" AND BUILD_TESTING)
    # By pass CONFIG setting. No optimzation
    list(APPEND EXTRA_COMPILER_OPTIONS "-O0")
else()
if(CONFIG_COMPILER_OPTIMIZATION_SIZE)
    list(APPEND EXTRA_COMPILER_OPTIONS "-Os")
    if(CMAKE_C_COMPILER_ID MATCHES "GNU")
        list(APPEND EXTRA_COMPILER_OPTIONS "-freorder-blocks")
    endif()
elseif(CONFIG_COMPILER_OPTIMIZATION_DEFAULT)
    list(APPEND EXTRA_COMPILER_OPTIONS "-Og")
elseif(CONFIG_COMPILER_OPTIMIZATION_NONE)
    list(APPEND EXTRA_COMPILER_OPTIONS "-O0")
elseif(CONFIG_COMPILER_OPTIMIZATION_PERF)
    list(APPEND EXTRA_COMPILER_OPTIONS "-O2")
endif()
endif()

message(STATUS "Building using IDF VERSION: $ENV{IDF_VERSION}")
if ("$ENV{IDF_VERSION}" VERSION_GREATER_EQUAL "5.0.0")
    set (IDF_VER_5 TRUE)
else()
    set (IDF_VER_5 FALSE)
endif()
# Check IDF version.
if (IDF_VER_5)
    if (NOT "$ENV{IDF_VERSION}" VERSION_GREATER_EQUAL "5.3.2")
        message( FATAL_ERROR "${IDF_VER}: Not using required version when building (>= \"5.3.2\")")
    endif()
else()
    if (NOT "$ENV{IDF_VERSION}" VERSION_GREATER_EQUAL "4.4.6")
        message( FATAL_ERROR "${IDF_VER}: Not using required version when building (>= \"4.4.6\")")
    endif()
    if (NOT "$ENV{IDF_VERSION}" VERSION_GREATER_EQUAL "4.4.8")
        message( WARNING "${IDF_VER}: Not using preferred version when building (>= \"4.4.8\")")
    endif()
endif()

#Fix for BLE
#add_compile_definitions(MYNEWT_VAL_BLE_GATT_MAX_PROCS=8)
#add_compile_definitions(ESP_PLATFORM)
#add_compile_definitions(IDF_VER)
#add_compile_definitions(_GNU_SOURCE)
#IDF VER 4.4.x
message(STATUS "IDF_VER_5 - ${IDF_VER_5}")
if (NOT IDF_VER_5)
list (APPEND EXTRA_COMPILER_OPTIONS "-fstrict-volatile-bitfields" "-ffunction-sections" "-fdata-sections" "-std=gnu99" "-Wall" "-Wextra" "-Wno-unused-parameter" "-ggdb" )
list (APPEND EXTRA_COMPILER_OPTIONS "-fmacro-prefix-map=${CMAKE_SOURCE_DIR}=.")
else()
#IDF VER 5.3.2
list (APPEND EXTRA_COMPILER_OPTIONS "-ffunction-sections" "-fdata-sections" "-fstrict-volatile-bitfields" "-Wall" "-Wextra" "-Werror=all" "-Wno-unused-parameter" "-gdwarf-4" "-ggdb" "-fno-jump-tables" "-fno-tree-switch-conversion" "-std=gnu17" "-fstack-protector" "-Wno-old-style-declaration")
list (APPEND EXTRA_COMPILER_OPTIONS "-fmacro-prefix-map=${CMAKE_SOURCE_DIR}=.")
list (APPEND EXTRA_COMPILER_OPTIONS "-Wno-error=format" "-Wno-format" "-Wno-address-of-packed-member")
endif()
if (${IDF_TARGET} STREQUAL "linux")
list (APPEND EXTRA_COMPILER_OPTIONS "-Wno-unused-parameter" "-Wno-error=unused-but-set-variable" "-Wno-error=unused-variable" )
endif()
if (${IDF_TARGET} STREQUAL "esp32c3")
#set(compile_options "-Wno-error=format="
#                    "-nostartfiles"
#                    "-Wno-format")
list (APPEND EXTRA_COMPILER_OPTIONS "-Wno-error=format=" "-nostartfiles" "-Wno-format")
# No external memory. Need to reduce framework memory consumption
list (APPEND EXTRA_COMPILER_DEFINITIONS "TO_BROKER_RINGBUFFER_SIZE=2048" "TO_CONNECTOR_RINGBUFFER_SIZE=1024" "SUBSCRIPTION_DEPTH=512" "ROUTE_DEPTH=512" "INSTANCE_DEPTH=128")
#list (APPEND EXTRA_COMPILER_DEFINITIONS "MYNEWT_VAL_BLE_GATT_MAX_PROCS=5")
elseif(${IDF_TARGET} STREQUAL "esp32c2")
list (APPEND EXTRA_COMPILER_OPTIONS "-Wno-error=format=" "-nostartfiles" "-Wno-format")
list (APPEND EXTRA_COMPILER_DEFINITIONS "TO_BROKER_RINGBUFFER_SIZE=2048" "TO_CONNECTOR_RINGBUFFER_SIZE=1024" "SUBSCRIPTION_DEPTH=512" "ROUTE_DEPTH=128" "INSTANCE_DEPTH=128" "INVENTORY_DEPTH=128")
else()
#list (APPEND EXTRA_COMPILER_DEFINITIONS "MYNEWT_VAL_BLE_GATT_MAX_PROCS=8")
endif()

list (APPEND EXTRA_COMPILER_DEFINITIONS ${FRAMEWORK_MODULES} "ESP_PLATFORM" "IDF_VER" "_GNU_SOURCE")
if (IDF_VER_5)
	list (APPEND EXTRA_COMPILER_DEFINITIONS "_GLIBCXX_USE_POSIX_SEMAPHORE" "_GLIBCXX_HAVE_POSIX_SEMAPHORE")
endif()
if (DEFINED BUILD_PRODUCT_ID)
list (APPEND EXTRA_COMPILER_DEFINITIONS "BUILD_PRODUCT_ID=\"${BUILD_PRODUCT_ID}\"")
endif()

if (${IDF_TARGET} STREQUAL "linux")
list (APPEND EXTRA_COMPILER_DEFINITIONS "UNITTEST_BUILD")
endif()

# Make them visible
set(EXTRA_COMPILER_OPTIONS ${EXTRA_COMPILER_OPTIONS} PARENT_SCOPE)
set(EXTRA_COMPILER_DEFINITIONS ${EXTRA_COMPILER_DEFINITIONS} PARENT_SCOPE)
# For hmi data build. These must be set in project_specific.cmake
set(HMI_DATA_SOURCE_DIRS ${HMI_DATA_SOURCE_DIRS} PARENT_SCOPE)
set(EXCLUDE_HMI_DATA_SOURCES ${EXCLUDE_HMI_DATA_SOURCES} PARENT_SCOPE)
set(HMI_DATA_INCLUDE_DIRS ${HMI_DATA_INCLUDE_DIRS} PARENT_SCOPE)
set(EXTRA_HMI_CODE_SOURCE_DIRS ${EXTRA_HMI_CODE_SOURCE_DIRS} PARENT_SCOPE)
set(EXTRA_HMI_CODE_INCLUDE_DIRS ${EXTRA_HMI_CODE_INCLUDE_DIRS} PARENT_SCOPE)
set(GEN_HMI_DATA_SOURCE_DIR ${GEN_HMI_DATA_SOURCE_DIR} PARENT_SCOPE)
set(GEN_HMI_DATA_EXE_ARGS ${GEN_HMI_DATA_EXE_ARGS} PARENT_SCOPE)
set(IDF_VER_5 ${IDF_VER_5} PARENT_SCOPE)
